# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_projects', '0009_auto_20161102_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ovp_organizations.Organization'),
        ),
    ]
