# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_projects', '0014_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applied_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together=set([('email', 'project')]),
        ),
    ]
