# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_projects', '0028_auto_20170126_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='minimum_age',
            field=models.IntegerField(default=0),
        ),
    ]
