# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_projects', '0035_auto_20170323_1933'),
        ('ovp_projects', '0035_auto_20170302_2231'),
    ]

    operations = [
    ]
