# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_projects', '0041_volunteerrole_applied_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Mode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovp_core.GoogleAddress', verbose_name='address'),
        ),
    ]
